# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpaceTracePlugin
                                 A QGIS plugin
 Draws the spacecraft's flight path over the Earth's surface
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-14
        copyright            : (C) 2025 by Yuriy Malyshev
        email                : yuaren@yandex.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpaceTracePlugin class from file SpaceTracePlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Space_trace import SpaceTracePlugin
    return SpaceTracePlugin(iface)
