# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'Space_trace_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SpaceTracePluginDialogBase(object):
    def setupUi(self, SpaceTracePluginDialogBase):
        SpaceTracePluginDialogBase.setObjectName("SpaceTracePluginDialogBase")
        SpaceTracePluginDialogBase.resize(855, 565)
        self.verticalLayout = QtWidgets.QVBoxLayout(SpaceTracePluginDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Поле для ввода NORAD ID спутника
        self.lineEditSatID = QtWidgets.QLineEdit(SpaceTracePluginDialogBase)
        self.lineEditSatID.setObjectName("lineEditSatID")
        self.verticalLayout.addWidget(self.lineEditSatID)
        
        # Поле выбора даты с календарём, по умолчанию установлена текущая системная дата
        self.dateEdit = QtWidgets.QDateEdit(SpaceTracePluginDialogBase)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDate(QtCore.QDate.currentDate())  # Установка текущей даты
        self.verticalLayout.addWidget(self.dateEdit)
        
        # Поле для выбора шага в минутах
        self.spinBoxStepMinutes = QtWidgets.QDoubleSpinBox(SpaceTracePluginDialogBase)
        self.spinBoxStepMinutes.setMinimum(0.1)
        self.spinBoxStepMinutes.setMaximum(60.0)
        self.spinBoxStepMinutes.setSingleStep(5.0)
        self.spinBoxStepMinutes.setProperty("value", 0.5)
        self.spinBoxStepMinutes.setObjectName("spinBoxStepMinutes")
        self.verticalLayout.addWidget(self.spinBoxStepMinutes)
        
        # Горизонтальный layout для поля ввода пути и кнопки "Browse"
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        # Поле ввода пути для сохранения shapefile
        self.lineEditOutputPath = QtWidgets.QLineEdit(SpaceTracePluginDialogBase)
        self.lineEditOutputPath.setObjectName("lineEditOutputPath")
        self.horizontalLayout.addWidget(self.lineEditOutputPath)
        
        # Кнопка для открытия диалога выбора файла
        # Текст кнопки содержит подсказку: оставьте поле пустым для создания временного слоя
        self.pushButtonBrowse = QtWidgets.QPushButton(SpaceTracePluginDialogBase)
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.horizontalLayout.addWidget(self.pushButtonBrowse)
        
        # Добавление горизонтального layout в основной вертикальный layout
        self.verticalLayout.addLayout(self.horizontalLayout)
        
        # Чекбокс для автоматической загрузки созданного слоя в проект
        self.checkBoxAddLayer = QtWidgets.QCheckBox(SpaceTracePluginDialogBase)
        self.checkBoxAddLayer.setObjectName("checkBoxAddLayer")
        self.checkBoxAddLayer.setChecked(True)
        self.verticalLayout.addWidget(self.checkBoxAddLayer)
        
        # Создание стандартных кнопок (OK/Cancel)
        self.buttonBox = QtWidgets.QDialogButtonBox(SpaceTracePluginDialogBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SpaceTracePluginDialogBase)
        self.buttonBox.accepted.connect(SpaceTracePluginDialogBase.accept)  # type: ignore
        self.buttonBox.rejected.connect(SpaceTracePluginDialogBase.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SpaceTracePluginDialogBase)
        
        # Подключение сигнала кнопки "Browse" к слоту для открытия диалога выбора файла
        self.pushButtonBrowse.clicked.connect(self.browseFile)

    def retranslateUi(self, SpaceTracePluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        SpaceTracePluginDialogBase.setWindowTitle(_translate("SpaceTracePluginDialogBase", "Space trace"))
        self.lineEditSatID.setPlaceholderText(_translate("SpaceTracePluginDialogBase", "Enter satellite's NORAD ID"))
        self.lineEditOutputPath.setPlaceholderText(_translate("SpaceTracePluginDialogBase", "Specify the path to save the shapefile."))
        self.pushButtonBrowse.setText(_translate("SpaceTracePluginDialogBase", "Browse (оставьте пустым для временного слоя)"))
        self.checkBoxAddLayer.setText(_translate("SpaceTracePluginDialogBase", "Добавить созданный слой в проект"))
    
    # Слот для открытия диалога выбора файла с возможностью указания имени файла
    def browseFile(self):
        file, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Select File", "", "Shapefiles (*.shp);;All Files (*)")
        if file:
            self.lineEditOutputPath.setText(file)
