# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Space_trace_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SpaceTracePluginDialogBase(object):
    def setupUi(self, SpaceTracePluginDialogBase):
        SpaceTracePluginDialogBase.setObjectName("SpaceTracePluginDialogBase")
        SpaceTracePluginDialogBase.resize(855, 565)
        self.verticalLayout = QtWidgets.QVBoxLayout(SpaceTracePluginDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditSatID = QtWidgets.QLineEdit(SpaceTracePluginDialogBase)
        self.lineEditSatID.setObjectName("lineEditSatID")
        self.verticalLayout.addWidget(self.lineEditSatID)
        self.dateEdit = QtWidgets.QDateEdit(SpaceTracePluginDialogBase)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.spinBoxStepMinutes = QtWidgets.QDoubleSpinBox(SpaceTracePluginDialogBase)
        self.spinBoxStepMinutes.setMinimum(0.1)
        self.spinBoxStepMinutes.setMaximum(60.0)
        self.spinBoxStepMinutes.setSingleStep(5.0)
        self.spinBoxStepMinutes.setProperty("value", 0.5)
        self.spinBoxStepMinutes.setObjectName("spinBoxStepMinutes")
        self.verticalLayout.addWidget(self.spinBoxStepMinutes)
        self.lineEditOutputPath = QtWidgets.QLineEdit(SpaceTracePluginDialogBase)
        self.lineEditOutputPath.setObjectName("lineEditOutputPath")
        self.verticalLayout.addWidget(self.lineEditOutputPath)
        
        # Исправленный код для создания кнопок
        self.buttonBox = QtWidgets.QDialogButtonBox(SpaceTracePluginDialogBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)  # Ориентация кнопок
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)  # Использование QDialogButtonBox из QtWidgets
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SpaceTracePluginDialogBase)
        self.buttonBox.accepted.connect(SpaceTracePluginDialogBase.accept)  # type: ignore
        self.buttonBox.rejected.connect(SpaceTracePluginDialogBase.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SpaceTracePluginDialogBase)

    def retranslateUi(self, SpaceTracePluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        SpaceTracePluginDialogBase.setWindowTitle(_translate("SpaceTracePluginDialogBase", "Space trace"))
        self.lineEditSatID.setPlaceholderText(_translate("SpaceTracePluginDialogBase", "Enter satellite's NORAD ID"))
        self.lineEditOutputPath.setPlaceholderText(_translate("SpaceTracePluginDialogBase", "Specify the path to save the shapefile."))

