# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Space_trace_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .Space_trace_dialog_class import Ui_SpaceTracePluginDialogBase

class SpaceTracePluginDialog(QtWidgets.QDialog, Ui_SpaceTracePluginDialogBase):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.lineEditSatID.setValidator(QtGui.QIntValidator(1, 999999, self))
        
    def appendLog(self, message):
        self.textEditLog.append(message)
        
    def switch_to_log_tab(self):
        """
        Switch the tab widget to the Log tab.
        """
        self.tabWidget.setCurrentIndex(1)